OBPIH-6682 add test for receive happy path
openboxes/openboxes-e2e pull request #15
Opened 2024-10-01 15:31 UTC by kkrawczyk123

Add 1st test for receiving workflow. I am aware that some of the selectors are not perfect and probably I will have to improve something. All steps described in the ticket should be covered. @drodzewicz please review it as it is now.

2024-10-08 15:54 UTC, kkrawczyk123 commented
@drodzewicz I have a problem with asserting the Remaining column on the checking page, can you please take a look at it? I am not sure why it doesn't work.

2024-10-09 11:17 UTC, drodzewicz requested changes

2024-10-09 11:17 UTC, drodzewicz commented on src/pages/receiving/components/CheckTable.ts
> +  }
In the PR I pushed https://github.com/openboxes/openboxes/pull/4887 I added addiitonal attributes for the check table cells so please refactor these methods accordigly.

Also lets make this method more generic so we can use it on other columns, so something like: 
```suggestion
  getCellValue(row: number, column: string) {
    return this.table
      .getByRole('row')
      .nth(row)
      .getByRole("cell", { name: column, exact: true })
  }
```

and the use it in the following way
```ts
     await expect(
        receivingPage.checkStep.table.getCellValue(1, "Remaining")
      ).toContainText('10');
```

2024-10-11 09:00 UTC, drodzewicz approved these changes

2024-10-11 09:00 UTC, merged